# 自带图标: https://primer.style/design/foundations/icons
plugins:
  - jekyll-octicons

# 默认主题
theme: null

# 压缩页面, 默认关闭
compress: true

# 简写代码, 默认关闭
shortcodes:
  - mermaid
  - note
  - warn
  - tip
  - danger

# 文档依赖
unpkg:
  primer: https://unpkg.com/@primer/css@20.8.2/dist/primer.css
  jquery: https://unpkg.com/jquery@3.6.3/dist/jquery.min.js
  mermaid: https://unpkg.com/mermaid@9.4.0/dist/mermaid.esm.min.mjs
